# Generated by Django 4.1.7 on 2023-04-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
