# Generated by Django 4.1.7 on 2023-04-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(default='Все подробности на Сайте', max_length=10000, null=True),
        ),
    ]
